apiVersion: v1
kind: Pod
metadata: 
  labels:
      name: ping
      tier: 
  name: pingapi
  namespace: pingpong
spec:
  containers:
  - env:
    - name: SERVER_PORT
      value: "8090"
    - name: CACHE_TYPE
      value: redis
    - name: CACHE_HOST
      value: redis
    - name: CACHE_PORT
      value: "6379"
    image: 
    imagePullPolicy: IfNotPresent
    name: ping
    ports:
    - containerPort: 8090
      name: tcp
      protocol: TCP
    resources: {}
