apiVersion: v1
kind: Pod
metadata: 
  labels:
      name: redis
      tier: cache
  name: redis
  namespace: pingpong
spec:
  containers:
  - name: redis
    image: redis:8.0-M01
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 6379
      protocol: TCP
    resources: {}

