apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: pingpong
  labels:
    name: redisservice
spec:
  selector:
    name: redis 
  ports:
   - port: 6379
     targetPort: 6379
     protocol: TCP
