apiVersion: apps/v1
kind: Deployment
metadata:
  name: pongapi
  namespace: pingpong
spec:
  selector:
    matchLabels:
      name: pong
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        name: pong
        tier: frontend
    spec:
      containers:
      - name: pong
        image: kumsub/pong:v1
        ports:
        - name: tcp
          containerPort: 8090
        env:
        - name: CACHE_TYPE
          value: redis
        - name: CACHE_HOST
          value: redis
        - name: CACHE_PORT
          value: "6379"
