apiVersion: v1
kind: Service
metadata:
  name: pingservice
  namespace: pingpong
  labels:
    name: pingservice
spec:
  selector:
    name: ping 
    tier: frontend
  type: LoadBalancer
  ports:
   - port: 8090
     targetPort: 8090
     protocol: TCP
