apiVersion: v1
kind: Service
metadata:
  name: pongservice
  namespace: pingpong
  labels:
    name: pongservice
spec:
  selector:
    name: pong
    tier: frontend
  type: ClusterIP
  ports:
   - port: 9090
     targetPort: 9090
     protocol: TCP
